### ISSUE TITLE
TODO : Show latest message in each room card

### ISSUE THREAD

**Issue by posaune0423** [posaune0423/next-firebase-chatapp#14]
- [ ] Create RoomCard component and separate it from RoomList component.
- [ ] Pass `roomId` as a props in iteration from RoomList to RoomCard.
- [ ] Fetch the latest **text** message by the passed `roomId` in the RoomCard component.
- [ ] Display the message under the room title.
